# Generated by Django 6.0.3 on 2026-09-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cropdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='name_mr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='name_pa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='name_mr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='name_pa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cropdataset',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Has this has been added to the Vector DB?'),
        ),
    ]
